// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Observable } from 'rxjs/Rx';
import { Subject } from 'rxjs/Subject';

@Component({
	selector: 'app-main',
	template: `
	<p>Hello, {{greeting}}</p>
	(counter: {{counter}})
	(doubleCounter: {{doubleCounter}})
	(tripleCounter: {{tripleCounter}})
	(unrelated: {{unrelated}})
	<button (click)="increment()">increment</button>
	<button (click)="incrementUnrelated()">increment unrelated</button>
	`
})
export class AppComponent {

	greeting = 'World';
	counter = 0;
	doubleCounter = 0;
	tripleCounter = 0;
	unrelated = 0;

	increment() {
		console.log('incrementing');
		this.counter += 1;
		this.doubleCounter = this.counter * 2;			// reactivo?
		this.tripleCounter = this.doubleCounter * 3;
	}

	incrementUnrelated() {
		console.log('incrementing unrelated');
		this.unrelated += 100;
	}
}

// react/app.js
class App extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			greeting: 'World',
			counter: 0,
			unrelated: 0,
		}
		window.globalApp = this;
    }
    increment() {
    	console.log('incrementing');
		this.setState({counter: this.state.counter + 1});
		// this.state.counter = this.state.counter + 1;
	}
	incrementUnrelated() {
		this.setState({unrelated: this.state.unrelated + 100});
	}
	render() {
		console.log('rendering');
		const doubleCounter = this.state.counter * 2;
		console.log('calculating doubleCounter');
		const tripleCounter = doubleCounter * 3;
		console.log('calculating tripleCounter');
		return (<p>
			Hello {this.state.greeting}! 
			(counter: {this.state.counter})
			(doubleCounter: {doubleCounter})
			(tripleCounter: {tripleCounter})
			(unrelated: {this.state.unrelated})
			<button onClick={this.increment.bind(this)}>increment</button>
			<button onClick={this.incrementUnrelated.bind(this)}>increment unrelated</button>
		</p>);
	}
}

ReactDOM.render(<App/>, document.getElementById('app'));
