// react-ecommerce/src/Price.js
import React from 'react';

// export default class Price extends React.Component {
//     render() {
//         const formattedPrice = this.props.price.toLocaleString('es-ES', {
//             style: 'currency', currency: 'EUR', currencyDisplay: 'symbol'
//         });
//         return <span>{formattedPrice}</span>;
//     }
// }

export default function Price(props) {
  const formattedPrice = props.price.toLocaleString('es-ES', {
    style: 'currency', currency: 'EUR', currencyDisplay: 'symbol',
  });

  console.log('rendering Price', formattedPrice);
  return <span>{formattedPrice}</span>;
}

// vue-ecommerce/src/components/Price.vue
<template>
  <span>{{trace(formattedPrice)}}</span>
</template>

<script>
  export default {
    props: {
      price: Number,
    },
    computed: {
      formattedPrice() {
        return this.price.toLocaleString('es-ES', {style: 'currency', currency: 'EUR', currencyDisplay: 'symbol'});
      },
    },
    methods: {
      trace(s) {
        console.log('rendering price', s);
        return s;
      },
    },
  };
</script>

<style lang="less" rel="stylesheet/less">
</style>
